config/routes.rb
Soshi::Engine.routes.draw do
  root to: "posts#index"

  resources :posts, except: [:show]
  resources :tags, only: [:index, :show]

  resources :categories, param: :slug, only: [:index, :new, :create]
  resources :categories, param: :slug, path: '/', except: [:index, :new, :create] do
    resources :posts, path: '/', only: [:show]
  end
end

app/models/soshi/application_record.rb
module Soshi
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/soshi/category.rb
module Soshi
  class Category < ApplicationRecord
    has_many :posts
    CUSTOM_PROHIBITED_WORDS = []

    validates :name, presence: true, uniqueness: { case_sensitive: false }
    SLUG_REGEX = /\A[a-zA-Z0-9\-_]+\z/
    validates :slug,
      presence: true,
      format: {with: SLUG_REGEX},
      uniqueness: { case_sensitive: false }
    validate :slug_cannot_be_assigned_prohibited_words

    def to_param
      slug
    end

    def slug_cannot_be_assigned_prohibited_words
      prohibited_words = ['posts', 'categories', 'tags'] + CUSTOM_PROHIBITED_WORDS
      errors.add(:slug, "に「#{slug}」は使用できません。") if prohibited_words.include?(slug)
    end
  end
end

app/models/soshi/post.rb
module Soshi
  class Post < ApplicationRecord
    belongs_to :category
    acts_as_paranoid
    acts_as_taggable

    validates :title, presence: true
    validates :body, presence: true
    validates :description, presence: true

    has_attached_file :image,
      styles: { ogp: "1200x630#", small: "400x210#", thumbnail: "200x105#" },
      default_style: :ogp,
      url: "/uploads/:hash",
      hash_secret: "longSecretString",
      default_url: "/default-ogp-image.png"
    validates_attachment :image, presence: true, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

    enum status: {draft: 0, published: 1}

    def published!
      self.update(status: 1, published_at: Time.current)
    end

    def draft!
      self.update(status: 0, published_at: nil)
    end
  end
end

app/controllers/soshi/application_controller.rb
module Soshi
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/soshi/categories_controller.rb
require_dependency "soshi/application_controller"

module Soshi
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    # GET /categories
    def index
      @categories = Category.all
    end

    # GET /categories/1
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to @category, notice: 'Category was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Category was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Category was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find_by(slug: params[:slug])
      end

      # Only allow a trusted parameter "white list" through.
      def category_params
        params.require(:category).permit(:name, :slug)
      end
  end
end

app/controllers/soshi/posts_controller.rb
require_dependency "soshi/application_controller"

module Soshi
  class PostsController < ApplicationController
    before_action :set_post, only: [:edit, :update, :destroy]
    before_action :set_used_tags, only: [:new, :edit, :create, :update]

    # GET /posts
    def index
      @posts = Post.all
    end

    # GET /posts/1
    def show
      category = Category.find_by!(slug: params[:category_slug])
      @post = Post.find_by!(id: params[:id], category: category)
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    def create
      @post = Post.new(post_params)

      if @post.save(validate: !params[:draft].present?)
        change_status
        if params[:draft].present?
          redirect_to edit_post_path(@post), notice: 'Post was successfully saved.'
        else
          redirect_to category_post_path(@post.category, @post), notice: 'Post was successfully created.'
        end
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      @post.assign_attributes(post_params)
      if @post.save(validate: !params[:draft].present?)
        change_status
        if params[:draft].present?
          redirect_to edit_post_path(@post), notice: 'Post was successfully to private.'
        else
          redirect_to category_post_path(@post.category, @post), notice: 'Post was successfully updated.'
        end
      else
        render :edit
      end
    end

    # DELETE /posts/1
    def destroy
      @post.draft!
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

      def set_used_tags
        @used_tags = ActsAsTaggableOn::Tag.all
      end

      # Only allow a trusted parameter "white list" through.
      def post_params
        params.require(:post).permit(
          :title,
          :body,
          :category_id,
          :tag_list,
          :description,
          :image,
        )
      end

      def change_status
        if params[:draft].present?
          @post.draft! 
        else
          @post.published! if @post.draft?
        end
      end
  end
end

app/controllers/soshi/tags_controller.rb
require_dependency "soshi/application_controller"

module Soshi
  class TagsController < ApplicationController
    def index
      @tags = ActsAsTaggableOn::Tag.all
    end

    def show
      @tag = ActsAsTaggableOn::Tag.find(params[:id])
      @posts = Post.tagged_with(@tag.name)
    end
  end
end

app/helpers/soshi/application_helper.rb
module Soshi
  module ApplicationHelper
  end
end

app/helpers/soshi/categories_helper.rb
module Soshi
  module CategoriesHelper
  end
end

app/helpers/soshi/markdown_helper.rb
module Soshi
  module MarkdownHelper
    def markdown(text)
      renderer_options = {
        hard_wrap: true,
        xhtml: true,
      }
      renderer = Redcarpet::Render::HTML.new(renderer_options)

      extensions = {
        autolink: true,
        space_after_headers: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        tables: true,
        lax_html_blocks: true,
        strikethrough: true
      }

      markdown = Redcarpet::Markdown.new(renderer, extensions)
      markdown.render(text)
    end
  end
end

app/helpers/soshi/posts_helper.rb
module Soshi
  module PostsHelper
  end
end

app/helpers/soshi/tags_helper.rb
module Soshi
  module TagsHelper
  end
end

app/views/layouts/soshi/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soshi</title>
  <%= stylesheet_link_tag    "soshi/application", media: "all", 'data-turbolinks-eval': false %>
  <%= javascript_include_tag "soshi/application", 'data-turbolinks-eval': false %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/soshi/categories/_form.html.slim
= form_with(model: category, local: true) do |form|
  - if category.errors.any?
    #error_explanation
      h2 #{pluralize(category.errors.count, "error")} prohibited this category from being saved
      ul
        - category.errors.full_messages.each do |message|
          li #{message}

  .field
    = form.label :name
    = form.text_field :name, id: :category_name

  .field
    = form.label :slug
    = form.text_field :slug, id: :category_slug

  .actions
    = form.submit

app/views/soshi/categories/edit.html.slim
h1 Editing Category

= render 'form', category: @category

= link_to 'Show', @category
br
= link_to 'Back', categories_path

app/views/soshi/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th>Deleted at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.slug %></td>
        <td><%= category.deleted_at %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/soshi/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/soshi/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @category.slug %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @category.deleted_at %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/soshi/posts/_form.html.slim
= bootstrap_form_for @post do |f|
  - if @post.errors.any?
    ul
      - @post.errors.full_messages.each do |message|
        li
          = message

  = f.text_field :title
  = f.text_area :body, cols: 30, rows: 40, class: 'soshi-markdown'
  = f.collection_select :category_id, Soshi::Category.all, :id, :name
  .form-group
    = f.label :tag_list, "Tags", class: 'control-label'
    = text_field_tag 'post[tag_list]', @post.tag_list.join(',')
    javascript:
      let usedTags = #{raw @used_tags.pluck(:name)};
  = f.text_area :description, cols: 30, rows: 2
  = f.file_field :image
  #image-preview.image-preview
    img src="#{@post.persisted? && @post.image.present? ? @post.image.url : ''}"

  .form-group
    label Status : #{@post.status}
    br
    - if @post.published?
      = f.submit 'Update post', class: 'btn btn-default'
      = f.submit 'To private', name: 'draft', class: 'btn btn-default'
    - else
      = f.submit 'Publish post', class: 'btn btn-default'
      = f.submit 'Save as draft', name: 'draft', class: 'btn btn-default'
    br
    = link_to 'Delete post', @post, method: :delete, data: {confirm: 'Are you sure?'}

app/views/soshi/posts/edit.html.slim
h1 Editing Post

= render 'form', post: @post

= link_to 'Show', @post
br
= link_to 'Back', posts_path

app/views/soshi/posts/index.html.slim
h1 Posts
table
  thead
    tr
      th Title
      th Body
      th Status
      th colspan="3" 
  tbody
    - @posts.each do |post|
      tr
        td = post.title
        td = post.body
        td = post.status
        td = link_to 'Show', post
        td = link_to 'Edit', edit_post_path(post)
        td = link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'}
br/
= link_to 'New Post', new_post_path
 

app/views/soshi/posts/new.html.slim
h1 New Post

= render 'form', post: @post

= link_to 'Back', posts_path

app/views/soshi/posts/show.html.slim
.title
  h2 Title
  = @post.title

.body
  h2 Body
  = markdown(@post.body).html_safe

.description
  p #{@post.description}

.tag
  ul.list-inline
    - @post.tags.each do |tag|
      li
        = link_to tag.name, tag_path(tag)
.image
  = image_tag @post.image.url

= link_to 'Edit', edit_post_path(@post)
|  | 
= link_to 'Back', posts_path

app/views/soshi/tags/index.html.slim
h1 Tags
ul
  - @tags.each do |tag|
    li
      = link_to tag.name, tag_path(tag)

app/views/soshi/tags/show.html.slim
h2 #{@tag.name}

h3 Posts
ul
  - @posts.each do |post|
    li
      = link_to post.title, post_path(post)

= link_to 'Back', tags_path